name: CI-BoB-Unitest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 우리코드 체크아웃
      - uses: actions/checkout@v2

      # 우리코드 돌릴 것
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # 설치 해야함...
      # 파이썬 유닛테스트 돌리기