name: CI-BoB-Unitest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 우리코드 체크아웃
      - uses: actions/checkout@v2

      # 우리코드 돌릴 것
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # 필요 환경/프레임워크/언어 설치
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # 필요 소프트웨어 패키지 설치
      - name: Install pip, pytest, flake8
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8

      # 코드 가독성/일관성 향상
      - name: Linting with flake8
        run:
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      # 파이썬 유닛테스트 돌리기
      - name: Run my unittest
        run: |
          pytest