name: CI-BOB-Unitest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      # 우리코드 체크아웃(가상머신에 우리코드 다운로드 (git clone))
      - name: Checkout my code
        uses: actions/checkout@v2

      # 필요 환경/프레임워크/언어 설치
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # 필요 소프트웨어 패키지 설치
      - name: Install pip, pytest, flake8
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8
      # 코드 가독성/일관성 향상
      - name: Linting with flake8
        run:
          flake8 

      # 파이썬 유닛테스를 돌려야함
      - name: Run my unittest
        run:
          pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: lovehyun/flask-app-auto
        tags: 1.0, latest
        registry: docker.io
        dockerfile: flask/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}